output_root: '/kaggle/working/output/'
data_dir: '/kaggle/input/'
experiment_name: "validation"
res: 320
batch_size: 32
num_workers: 2
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False
model_paths:
 - "/kaggle/working/output/checkpoints/potsdam_exp1.ckpt"

hydra:
  run:
    dir: "/kaggle/working/output/"
  output_subdir: "${hydra.run.dir}/${now:%Y-%m-%d_%H-%M-%S}"
#model_paths:
#  - "checkpoints/cocostuff27_dino_small.ckpt"
 # - "checkpoints/cityscapes_dino_small.ckpt"
#   - "checkpoints/potsdam_dino_vit_base.ckpt"
# model_paths:
#   - "/kaggle/input/potsdam_dino_vit_base.ckpt"

# hydra:
#   run:
#     dir: "."
#   output_subdir: ~
